# Generated by Django 3.1 on 2020-08-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200816_1154'),
        ('users', '0002_auto_20200816_1147'),
    ]

    operations = [
    ]
