# Generated by Django 3.1 on 2020-08-16 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Students',
        ),
    ]
