# Generated by Django 3.1 on 2020-08-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.IntegerField()),
                ('Center_Name', models.CharField(max_length=100)),
                ('LDCM_Name', models.CharField(max_length=100)),
                ('Reportee', models.CharField(max_length=100)),
                ('Batch_Type', models.CharField(max_length=100)),
                ('Batch_Code', models.CharField(max_length=100)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Course_Name2', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=1)),
                ('Start_Date', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Passouts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.IntegerField()),
                ('LCDM_Name', models.CharField(max_length=100)),
                ('LDC_Name', models.CharField(max_length=100)),
                ('Batch_Code', models.CharField(max_length=100)),
                ('Status', models.CharField(max_length=1)),
                ('Start_Date', models.IntegerField()),
                ('End_Date', models.IntegerField()),
                ('Course_Name', models.CharField(max_length=100)),
                ('Full_Name', models.CharField(max_length=100)),
                ('DOB', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region', models.IntegerField()),
                ('ReporteeLDCM', models.CharField(max_length=100)),
                ('LDC_Name', models.CharField(max_length=100)),
                ('Batch_Code', models.CharField(max_length=100)),
                ('Course_Name', models.CharField(max_length=100)),
                ('Start_Date', models.IntegerField()),
                ('End_Date', models.IntegerField()),
                ('Student_Id', models.IntegerField()),
                ('Student_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
