# Generated by Django 3.1 on 2020-08-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200816_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='batches',
            name='LDCM',
            field=models.CharField(default='', max_length=100),
        ),
    ]
